In [6]:
import numpy as np
np.__version__

'1.21.3'

In [7]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[0]

array([1, 2, 3, 4])

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [21]:
arr = np.arange(1,9)

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [24]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [25]:
arr = np.array([2,1,3,4,6,5,7,3,8,9])

In [26]:
np.sort(arr)

array([1, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array_example = np.array([[0,1,2,3],[4,5,6,7],[0,1,2,3],[4,5,6,7],[0,1,2,3],[4,5,6,7]])

In [29]:
print(array_example)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [30]:
array_example.ndim

2

In [32]:
array_example.size

24

In [33]:
array_example.shape

(6, 4)

In [34]:
arr_one = np.array([[1,2,3,4,5]])

In [35]:
arr_one.ndim

2

In [36]:
arr_one.size

5

In [37]:
arr_one.shape

(1, 5)

In [39]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [40]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [43]:
b=a.reshape(6,1)
print (b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [44]:
a = np.arange(6)

In [48]:
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [50]:
a2 = a[np.newaxis]
print (a2.shape)
print (a2[0][3])

(1, 6)
3


In [51]:
row_vector = a[np.newaxis,:]
print(row_vector.shape)
print (row_vector)

(1, 6)
[[0 1 2 3 4 5]]


In [53]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print (col_vector)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [55]:
a = np.arange(6)
a.shape

(6,)

In [56]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [57]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [63]:
data = np.arange(4)
print (data)
print (data[0])
print (data[0:2])
print (data[1:])
print (data[-2:])

[0 1 2 3]
0
[0 1]
[1 2 3]
[2 3]


In [64]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [65]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [67]:
five_up = (a>=5)

print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [69]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [74]:
c = a[(a>2)|(a>11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr1 = arr[3:8]
arr1

array([3, 4, 5, 6, 7])

In [80]:
a_1 = np.array([[1,1],[2,2]])
a_2 = np.array([[3,3],[4,4]])

In [81]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [82]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [85]:
arrsplit = np.arange(25)
arrsplit

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
a,b,c,d,e=np.hsplit(arrsplit,5)
b


array([5, 6, 7, 8, 9])

In [88]:
bview = arrsplit.view()
bview

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
A = np.array([[0.2495629469,0.2462596498270,0.6767634696],
             [0.8798797870,0.379379236927,0.89898934343],
             [0.898495298,0.232432423424,0.3434234243245]])
print(A)

[[0.24956295 0.24625965 0.67676347]
 [0.87987979 0.37937924 0.89898934]
 [0.8984953  0.23243242 0.34342342]]


In [96]:
A.sum()

0.89898934343

In [97]:
A.min()

0.232432423424

In [98]:
A.max()

0.89898934343

In [100]:
A.min(axis=1)

array([0.24625965, 0.37937924, 0.23243242])

In [101]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [102]:
np.random.random((3,2))

array([[0.49663759, 0.32196764],
       [0.77666404, 0.86687017],
       [0.88076197, 0.29141147]])

In [103]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [104]:
ones = np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

In [105]:
print (data + ones)

[[2. 3.]
 [4. 5.]]


In [108]:
a_1 = np.array([[1,2,3],[4,5,5]])
a_2 = np.array([[7,8],[9,10],[11,12]])

In [109]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [128, 142]])

In [113]:
observed = np.random.random ([3,2])
prediction = np.random.random ([3,2])

In [118]:
(1/observed.size) * np.sum(np.square((observed - prediction)))

0.010936946026784588